/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ssg;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

/**
 * App class test.
 */
class AppTest {
    @Test void appHasGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting SVP");
    }
}
