/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ssg;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;
import org.junit.jupiter.api.Test;
import ssg.page.PageDraft;
import ssg.tomlvaluetypewrapper.TomlIntegerWrapper;
import ssg.tomlvaluetypewrapper.TomlTableWrapper;
import ssg.tomlvaluetypewrapper.TomlValueTypeWrapper;



/**
 * App class test.
 */

@SuppressWarnings("PMD.TooManyMethods")
class PageDraftTest {

    @Test void createEmptyPageDraft() {
        PageDraft c = new PageDraft("");
        assertEquals("",c.getBuffer(),"Test page vide");
    }

    @SuppressWarnings("PMD.LawOfDemeter")
    @Test void createPageDraft() {
        HashMap<String, TomlValueTypeWrapper> a = new HashMap<>();
        a.put("un", new TomlIntegerWrapper(1));
        a.put("deux", new TomlIntegerWrapper(2));
        TomlTableWrapper b = new TomlTableWrapper(a);
        PageDraft e = new PageDraft(b, "");
        assertEquals("Optional[un : 1\ndeux : 2\n]",e.getMetadata().toString(),
                "Test page avec Metadata");
    }

}
