/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ssg.page;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;
import org.junit.jupiter.api.Test;
import ssg.page.PageDraft;
import ssg.tomlvaluetypewrapper.TomlIntegerWrapper;
import ssg.tomlvaluetypewrapper.TomlTableWrapper;
import ssg.tomlvaluetypewrapper.TomlValueTypeWrapper;

/**
 * Junit test class for TomlTableWrapper.
 */
@SuppressWarnings("PMD.TooManyMethods")
class PageDraftTest {

    @SuppressWarnings("PMD.LawOfDemeter")
    @Test void createPageDraft() {
        HashMap<String, TomlValueTypeWrapper> a = new HashMap<>();
        a.put("un", new TomlIntegerWrapper(1));
        a.put("deux", new TomlIntegerWrapper(2));
        PageDraft e = new PageDraft(a, "");
        String expected = "Optional[{un=1, deux=2}]";
        assertEquals(expected,e.getMetadata().toString(),"Test page avec Metadata");
    }

}
