/**
 * This Java source file was generated by the Gradle 'init' task.
 */

package ssg;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import ssg.myapplicationrunner.MyApplicationRunner;

/**
 * Main class.
 */
public class App {

    /**
     * Logger.
     */
    private static final Logger logger = LogManager.getLogger();

    /**
     * Return a text.
     *
     *@return "Hello World!"
     */
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Main.
     *
     * @param args main arguments
     */
    public static void main(String[] args) {

        logger.info("Launch app");
        MyApplicationRunner applicationRunner = new MyApplicationRunner(args);
        applicationRunner.run();
        System.exit(applicationRunner.getExitCode());

    }
}